spring.application.name=nexus-ai
spring.datasource.url=jdbc:h2:mem:nexusdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
server.port=8080

# Jira Integration
jira.url=https://nexus-ai-hack.atlassian.net
jira.email=langaliyajenil@gmail.com
jira.api-token=ATATT3xFfGF04jF7jjqqtcFHoKGP5hN1GZjx4ZIWxJr65dbAc1X6S9y0KStv_0UsOBeMPTDEHJT9PpDrjGL28Gvo6r8RFQIeM5rPXbL8XwB8m2RxHC5dR40QKnpp4MlHKokCh58qjuisVG86QXkL61hludufYAcJBsDvNlbdGGPsgsOB9aLFDx8=5111A447
jira.project-key=NEX
